DataFetchStrategy enhancement
oswaldobapvicjr/confectory pull request #32
Opened 2021-08-05 12:36 UTC by FernandoNSC5

Enhanced DataFetchStrategy to retrieve unsorted data in order to save computing cost

2021-08-11 01:10 UTC, FernandoNSC5 commented
@oswaldobapvicjr Now It's working just fine (:
![image](https://user-images.githubusercontent.com/32530166/128954522-307ee70d-eed9-4d66-9e89-3d97aabe57f0.png)

2021-08-11 03:26 UTC, oswaldobapvicjr requested changes
Good job! Just some small improvements in Javadoc and JUnit and then we'll be good to merge.
Feel free to get in touch if you need more insights on my comment about the JUnit tests.
Thanks!

2021-08-11 03:26 UTC, oswaldobapvicjr commented on confectory-core/src/main/java/net/obvj/confectory/DataFetchStrategy.java
> +    STRICT_UNSORTED {
Move the "{" sign to the next line

2021-08-11 03:26 UTC, oswaldobapvicjr commented on confectory-core/src/main/java/net/obvj/confectory/DataFetchStrategy.java
> +     */
Add the `@since 0.2.0` tag now

2021-08-11 03:26 UTC, oswaldobapvicjr commented on confectory-core/src/main/java/net/obvj/confectory/DataFetchStrategy.java
> +     */
Add the `@since 0.2.0` tag now

2021-08-11 03:26 UTC, oswaldobapvicjr commented on confectory-core/src/test/java/net/obvj/confectory/ConfigurationContainerTest.java
> +        assertTrue(responseValue.equals("string1") || responseValue.equals("string2"));
Always prefer to use `assertThat` which is more readable and better for troubleshooting:
`assertThat(container.getStringProperty(KEY_STRING), ... );

2021-08-11 03:26 UTC, oswaldobapvicjr commented on confectory-core/src/test/java/net/obvj/confectory/ConfigurationContainerTest.java
> +        assertTrue(responseValue.equals("string1") || responseValue.equals("string2"));
Same here

2021-08-12 01:40 UTC, oswaldobapvicjr commented on confectory-core/src/test/java/net/obvj/confectory/ConfigurationContainerTest.java
> +        assertThat(container.getStringProperty(KEY_STRING), either(containsString("string1")).or(containsString("string2"))); // CONF_NS1_PROPERTIES_2 (lenient)
```suggestion
        assertThat(container.getStringProperty(KEY_STRING), either(equalTo("string1")).or(equalTo("string2")));
```

2021-08-12 01:40 UTC, oswaldobapvicjr commented on confectory-core/src/test/java/net/obvj/confectory/ConfigurationContainerTest.java
> +        assertThat(container.getStringProperty(NAMESPACE1, KEY_STRING), either(containsString("string1")).or(containsString("string2")));
```suggestion
        assertThat(container.getStringProperty(NAMESPACE1, KEY_STRING), either(equalTo("string1")).or(equalTo("string2")));
```

2021-08-12 01:40 UTC, oswaldobapvicjr commented on confectory-core/src/test/java/net/obvj/confectory/ConfigurationContainerTest.java
> +    void getUnsortedStringProperty_namespaceAndKeyLenient_sameAsStrict() {
```suggestion
    void getStringProperty_namespaceAndKeyLenientUnsorted_sameAsStrictUnsorted() {
```

2021-08-12 01:40 UTC, oswaldobapvicjr commented on confectory-core/src/test/java/net/obvj/confectory/ConfigurationContainerTest.java
> +    void getUnsortedStringProperty_keyOnlyAndLenient_configurationWithoutNamespace() {
```suggestion
    void getStringProperty_keyOnlyAndLenientUnsorted_anyOfTheConfigurationsWithoutNamespace() {
```

2021-08-12 01:47 UTC, oswaldobapvicjr approved these changes
Approved ✔️

2021-08-12 01:48 UTC, merged